name: Build
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  build-project-ubuntu:
    name: Build Project (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0

  build-project-windows:
    name: Build Project (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0

  build-project-macos:
    name: Build Project (macOS)
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
